In [1]:
#collections
#list , tuple , set , string
#collection of semilar data type #array

numbers = [10, "Hello" , 78.0 , True]
print(numbers)

[10, 'Hello', 78.0, True]


In [ ]:
!pip install numpy

In [14]:
#NumPY #TPP
import numpy

numbers = numpy.array([10, True, False, 30 , "10"])

print(type(numbers))
print(type(numbers[1]))
print(numbers)


<class 'numpy.ndarray'>
<class 'numpy.str_'>
['10' 'True' 'False' '30' '10']


In [22]:
import numpy as np
numbers1 = np.array([10, 20, 30 , 40])
numbers2 = np.array([11, 22 , 33 , 44])
print(numbers1)
print(numbers2)

#add elemenets in array
numbers1 = np.append(numbers1 , [50 , 60 , 70])
numbers2 = np.append(numbers2 , [55 , 66, 77])

print(numbers1)
print(numbers2)

numbers3 = np.append(numbers1 , numbers2)
print(numbers3)

[10 20 30 40]
[11 22 33 44]
[10 20 30 40 50 60 70]
[11 22 33 44 55 66 77]
[10 20 30 40 50 60 70 11 22 33 44 55 66 77]


In [23]:
for i in range(len(numbers1)):
    print(numbers1[i])

10
20
30
40
50
60
70


In [30]:
#2 Data Array
axis = np.array([[1,2,3,4,5], [10, 20 , 30 , 40 ,50]])
print(axis)
print(axis[0][0])
print(axis[1][1])

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
1
20


In [39]:
#3 Data Array
axis = np.array([[[1,2,3,4,5], [10, 20 , 30 , 40 ,50] , [11 , 22 , 33 , 44, 55]]])

print(axis)
print(axis[0][1][1])


[[[ 1  2  3  4  5]
  [10 20 30 40 50]
  [11 22 33 44 55]]]
20
